package io.four.exception;

public class ExceptionHolder {

    public static Exception INVOKE_TIMEOUT = new InvokeTimeOutException("Time out");

}
